anguage: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install coveralls
  - pip install coverage
install:
  - pip install -r requirements.txt
  - pip install ".[test]" . # install package + test dependencies
script: coverage run setup.py test #pytest # run tests
after_success:
  - coveralls